// @generated by scripts/generate_seeded_conformance.py; do not edit.
#[test_only]
module integration_tests::seeded_conformance_generated {
    use cedra_framework::primary_fungible_store;
    use cedra_framework::timestamp;
    use reflection_core::reflection_router;
    use reflection_core::reflection_token;
    use std::signer;
    use test_amm::pool;
    use test_assets::mock_usd;
    use test_assets::test_faucet;

    fun setup(core: &signer, assets: &signer, amm: &signer, framework: &signer) {
        timestamp::set_time_has_started_for_testing(framework);
        reflection_token::initialize_for_test(core);
        mock_usd::initialize_for_test(assets);
        test_faucet::initialize(core, assets);
        pool::initialize(core, assets, amm);
    }

    #[test(
        core = @0xcafe,
        assets = @0xbabe,
        amm = @0xdead,
        framework = @0x1,
        alice = @0xa11ce,
        bob = @0xb0b,
        carol = @0xca401,
        dave = @0xda7e,
    )]
    fun seeded_python_move_conformance(
        core: &signer,
        assets: &signer,
        amm: &signer,
        framework: &signer,
        alice: &signer,
        bob: &signer,
        carol: &signer,
        dave: &signer,
    ) {
        setup(core, assets, amm, framework);

        // operation 1: faucet_grant
        test_faucet::configure(assets, 500000, 1, 0);
        test_faucet::claim_trfl(alice);
        // operation 2: faucet_grant
        test_faucet::configure(assets, 500000, 1, 0);
        test_faucet::claim_trfl(bob);
        // operation 3: faucet_grant
        test_faucet::configure(assets, 500000, 1, 0);
        test_faucet::claim_trfl(carol);
        // operation 4: faucet_grant
        test_faucet::configure(assets, 500000, 1, 0);
        test_faucet::claim_trfl(dave);
        // operation 5: mint_quote
        test_faucet::configure(assets, 1, 5000000, 0);
        test_faucet::claim_tusd(amm);
        // operation 6: mint_quote
        test_faucet::configure(assets, 1, 1000000, 0);
        test_faucet::claim_tusd(alice);
        // operation 7: mint_quote
        test_faucet::configure(assets, 1, 1000000, 0);
        test_faucet::claim_tusd(bob);
        // operation 8: mint_quote
        test_faucet::configure(assets, 1, 1000000, 0);
        test_faucet::claim_tusd(carol);
        // operation 9: mint_quote
        test_faucet::configure(assets, 1, 1000000, 0);
        test_faucet::claim_tusd(dave);
        // operation 10: seed_pool
        pool::seed_liquidity(
            core, amm, signer::address_of(alice), 2000000,
            2000000, 1,
        );
        // operation 11: sell
        pool::sell_trfl(carol, 1801, 0, 1_000);
        // operation 12: sell
        pool::sell_trfl(bob, 3887, 0, 1_000);
        // operation 13: transfer
        reflection_router::transfer(alice, signer::address_of(dave), 386);
        // operation 14: transfer
        reflection_router::transfer(dave, signer::address_of(alice), 178);
        // operation 15: sell
        pool::sell_trfl(dave, 1942, 0, 1_000);
        // operation 16: transfer
        reflection_router::transfer(bob, signer::address_of(alice), 1503);
        // operation 17: buy
        pool::buy_trfl(bob, 2198, 0, 1_000);
        // operation 18: transfer
        reflection_router::transfer(carol, signer::address_of(alice), 1149);
        // operation 19: add_liquidity
        pool::add_liquidity(
            alice, 1458, 1384,
            1, 1_000,
        );
        // operation 20: sell
        pool::sell_trfl(alice, 822, 0, 1_000);
        // operation 21: transfer
        reflection_router::transfer(bob, signer::address_of(dave), 1021);
        // operation 22: claim
        reflection_token::claim(dave, 1);
        // operation 23: buy
        pool::buy_trfl(carol, 2775, 0, 1_000);
        // operation 24: claim
        reflection_token::claim(carol, 6);
        // operation 25: sell
        pool::sell_trfl(carol, 3265, 0, 1_000);
        // operation 26: add_liquidity
        pool::add_liquidity(
            bob, 984, 1221,
            1, 1_000,
        );
        // operation 27: claim
        reflection_token::claim(bob, 20);
        // operation 28: buy
        pool::buy_trfl(alice, 4108, 0, 1_000);
        // operation 29: buy
        pool::buy_trfl(dave, 1449, 0, 1_000);
        // operation 30: remove_liquidity
        pool::remove_liquidity(
            bob, 267,
            1, 1, 1_000,
        );
        // operation 31: set_fee_bps
        reflection_token::set_fee_bps(core, 61);
        // operation 32: sell
        pool::sell_trfl(carol, 1950, 0, 1_000);
        // operation 33: sell
        pool::sell_trfl(alice, 3162, 0, 1_000);
        // operation 34: checkpoint_pool
        pool::checkpoint_lp_rewards(alice);
        // operation 35: transfer
        reflection_router::transfer(carol, signer::address_of(dave), 4227);
        // operation 36: sell
        pool::sell_trfl(dave, 2238, 0, 1_000);
        // operation 37: checkpoint_pool
        pool::checkpoint_lp_rewards(alice);
        // operation 38: checkpoint_pool
        pool::checkpoint_lp_rewards(alice);
        // operation 39: checkpoint_pool
        pool::checkpoint_lp_rewards(alice);
        // operation 40: buy
        pool::buy_trfl(dave, 3513, 0, 1_000);
        // operation 41: sell
        pool::sell_trfl(alice, 735, 0, 1_000);
        // operation 42: transfer_lp_shares
        pool::transfer_lp_shares(bob, signer::address_of(carol), 161);
        // operation 43: buy
        pool::buy_trfl(bob, 4181, 0, 1_000);
        // operation 44: buy
        pool::buy_trfl(bob, 459, 0, 1_000);
        // operation 45: add_liquidity
        pool::add_liquidity(
            bob, 1086, 2563,
            1, 1_000,
        );
        // operation 46: sell
        pool::sell_trfl(bob, 3379, 0, 1_000);
        // operation 47: transfer
        reflection_router::transfer(dave, signer::address_of(bob), 1646);
        // operation 48: transfer
        reflection_router::transfer(bob, signer::address_of(alice), 2490);
        // operation 49: add_liquidity
        pool::add_liquidity(
            dave, 163, 3802,
            1, 1_000,
        );
        // operation 50: set_fee_bps
        reflection_token::set_fee_bps(core, 53);
        // operation 51: buy
        pool::buy_trfl(carol, 3986, 0, 1_000);
        // operation 52: buy
        pool::buy_trfl(dave, 3997, 0, 1_000);
        // operation 53: transfer
        reflection_router::transfer(bob, signer::address_of(carol), 3265);
        // operation 54: claim
        reflection_token::claim(alice, 31);
        // operation 55: set_fee_bps
        reflection_token::set_fee_bps(core, 89);
        // operation 56: remove_liquidity
        pool::remove_liquidity(
            carol, 15,
            1, 1, 1_000,
        );
        // operation 57: transfer_lp_shares
        pool::transfer_lp_shares(carol, signer::address_of(alice), 45);
        // operation 58: transfer_lp_shares
        pool::transfer_lp_shares(bob, signer::address_of(dave), 1305);
        // operation 59: remove_liquidity
        pool::remove_liquidity(
            carol, 29,
            1, 1, 1_000,
        );
        // operation 60: claim
        reflection_token::claim(dave, 40);
        // operation 61: buy
        pool::buy_trfl(alice, 3102, 0, 1_000);
        // operation 62: buy
        pool::buy_trfl(alice, 2684, 0, 1_000);
        // operation 63: transfer
        reflection_router::transfer(bob, signer::address_of(carol), 771);
        // operation 64: claim_lp
        pool::claim_lp_rewards(alice, 1, 93);
        // operation 65: remove_liquidity
        pool::remove_liquidity(
            alice, 4358,
            1, 1, 1_000,
        );
        // operation 66: sell
        pool::sell_trfl(dave, 3681, 0, 1_000);
        // operation 67: transfer
        reflection_router::transfer(dave, signer::address_of(bob), 3319);
        // operation 68: buy
        pool::buy_trfl(carol, 3463, 0, 1_000);
        // operation 69: add_liquidity
        pool::add_liquidity(
            dave, 756, 1205,
            1, 1_000,
        );
        // operation 70: checkpoint_pool
        pool::checkpoint_lp_rewards(alice);
        // operation 71: sell
        pool::sell_trfl(bob, 1356, 0, 1_000);
        // operation 72: buy
        pool::buy_trfl(alice, 3438, 0, 1_000);
        // operation 73: sell
        pool::sell_trfl(alice, 3667, 0, 1_000);
        // operation 74: sell
        pool::sell_trfl(dave, 2297, 0, 1_000);

        let (index, remainder, shares, unallocated, lifetime_fees, materialized) =
            reflection_token::global_accounting();
        assert!(reflection_token::fee_bps() == 89, 1);
        assert!(index == 145621074240505212689, 2);
        assert!(remainder == 1699388, 3);
        assert!(shares == 3999609, 4);
        assert!(unallocated == 0, 5);
        assert!(lifetime_fees == 582, 6);
        assert!(materialized == 98, 7);
        let (aggregate_negative, aggregate_magnitude) =
            reflection_token::aggregate_correction();
        assert!(aggregate_negative == true, 8);
        assert!(aggregate_magnitude == 427359121992813219537989, 9);
        let (custody_shares, routed, core_rounding) =
            reflection_token::custody_accounting();
        assert!(custody_shares == 1994424, 10);
        assert!(routed == 244, 11);
        assert!(core_rounding == 1, 12);
        let (_, custody_negative, custody_magnitude, custody_settled, custody_pending) =
            reflection_token::custody_position_accounting();
        assert!(custody_negative == false, 13);
        assert!(custody_magnitude == 732304249739815834002303, 14);
        assert!(custody_settled == 244, 15);
        assert!(custody_pending == 47, 16);
        assert!(reflection_token::raw_balance(signer::address_of(alice)) == 512732, 20);
        assert!(reflection_token::pending_rewards(signer::address_of(alice)) == 42, 21);
        assert!(reflection_token::raw_balance(signer::address_of(bob)) == 492305, 22);
        assert!(reflection_token::pending_rewards(signer::address_of(bob)) == 51, 23);
        assert!(reflection_token::raw_balance(signer::address_of(carol)) == 501801, 24);
        assert!(reflection_token::pending_rewards(signer::address_of(carol)) == 66, 25);
        assert!(reflection_token::raw_balance(signer::address_of(dave)) == 498347, 26);
        assert!(reflection_token::pending_rewards(signer::address_of(dave)) == 32, 27);
        let (pool_rfl, pool_usd) = pool::reserves_view();
        assert!(pool_rfl == 1994424, 28);
        assert!(pool_usd == 2005253, 29);
        assert!(reflection_token::pool_pending_rewards() == 47, 30);
        assert!(reflection_token::reward_vault_balance() == 240, 31);
        assert!(
            reflection_token::raw_store_balance(reflection_token::distribution_vault())
                == 999999996000000,
            32,
        );
        assert!(primary_fungible_store::balance(signer::address_of(alice), mock_usd::metadata()) == 997968, 33);
        assert!(primary_fungible_store::balance(signer::address_of(bob), mock_usd::metadata()) == 999877, 34);
        assert!(primary_fungible_store::balance(signer::address_of(carol), mock_usd::metadata()) == 996731, 35);
        assert!(primary_fungible_store::balance(signer::address_of(dave), mock_usd::metadata()) == 1000171, 36);
        assert!(primary_fungible_store::balance(signer::address_of(amm), mock_usd::metadata()) == 3000000, 37);
        let (lp_status, lp_index, lp_remainder, lp_shares, lp_unallocated,
            lp_rounding, lp_received, lp_claimed, lp_liability) =
            pool::lp_epoch_accounting(1);
        assert!(lp_status == 1, 38);
        assert!(lp_index == 121909165358824845043, 39);
        assert!(lp_remainder == 891470, 40);
        assert!(lp_shares == 1999704, 41);
        assert!(lp_unallocated == 0, 42);
        assert!(lp_rounding == 1, 43);
        assert!(lp_received == 244, 44);
        assert!(lp_claimed == 93, 45);
        assert!(lp_liability == 150, 46);
        assert!(pool::lp_reward_vault_balance(1) == 151, 47);
        let (lp_aggregate_negative, lp_aggregate_magnitude) =
            test_amm::lp_rewards::epoch_aggregate_correction(1);
        assert!(lp_aggregate_negative == false, 48);
        assert!(lp_aggregate_magnitude == 217754395296522067241258, 49);
        let (owner_shares, negative, magnitude, claimed, pending) =
            test_amm::lp_rewards::position_accounting(1, signer::address_of(alice));
        assert!(owner_shares == 1997074, 50);
        assert!(negative == false, 51);
        assert!(magnitude == 426181019977608556576012, 52);
        assert!(claimed == 93, 53);
        assert!(pending == 150, 54);
        let (owner_shares, negative, magnitude, claimed, pending) =
            test_amm::lp_rewards::position_accounting(1, signer::address_of(bob));
        assert!(owner_shares == 332, 55);
        assert!(negative == false, 56);
        assert!(magnitude == 23332393997856369869336, 57);
        assert!(claimed == 0, 58);
        assert!(pending == 0, 59);
        let (owner_shares, negative, magnitude, claimed, pending) =
            test_amm::lp_rewards::position_accounting(1, signer::address_of(carol));
        assert!(owner_shares == 72, 60);
        assert!(negative == true, 61);
        assert!(magnitude == 3145141162725921819313, 62);
        assert!(claimed == 0, 63);
        assert!(pending == 0, 64);
        let (owner_shares, negative, magnitude, claimed, pending) =
            test_amm::lp_rewards::position_accounting(1, signer::address_of(dave));
        assert!(owner_shares == 2226, 65);
        assert!(negative == true, 66);
        assert!(magnitude == 228613877516216937384777, 67);
        assert!(claimed == 0, 68);
        assert!(pending == 0, 69);
        assert!(
            (pool::lp_reward_vault_balance(1) as u256)
                == lp_liability + (lp_unallocated as u256) + (lp_rounding as u256),
            70,
        );
        assert!(lp_received - lp_claimed == (pool::lp_reward_vault_balance(1) as u256),
            71);
        reflection_token::assert_accounting_backing();
    }
}
