[package]
name = "ReflectionIntegrationTests"
version = "0.2.0"
upgrade_policy = "compatible"

[dependencies]
CedraFramework = { git = "https://github.com/cedra-labs/cedra-framework.git", subdir = "cedra-framework", rev = "01e6ceafae19b900772b343a5af8ae236401e0a8" }
ReflectionCore = { local = "../reflection-core" }
TestAssets = { local = "../test-assets" }
TestAmm = { local = "../test-amm" }

[addresses]
integration_tests = "_"
reflection_core = "_"
test_assets = "_"
test_amm = "_"
bootstrap_lp = "_"

[dev-addresses]
integration_tests = "0xf00d"
reflection_core = "0xcafe"
test_assets = "0xbabe"
test_amm = "0xdead"
bootstrap_lp = "0xa11ce"
